# GitHub Ruleset for Culinaria Recipe App
# Copyright (c) 2024 Sabina Begum. All rights reserved.

name: "Culinaria Security & Quality Standards"
description: "Security and quality rules for the Culinaria recipe application"
enforcement: "active"
target:
  branch:
    - "main"
    - "develop"
    - "feature/*"
    - "hotfix/*"
    - "release/*"

# Branch Protection Rules
rules:
  # Require pull request reviews
  - name: "Require pull request reviews"
    conditions:
      ref_name:
        include:
          - "main"
          - "develop"
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true
      require_code_owner_reviews: false
      require_last_push_approval: true

  # Require status checks to pass
  - name: "Require status checks to pass"
    conditions:
      ref_name:
        include:
          - "main"
          - "develop"
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - "lint"
          - "type-check"
          - "build"
          - "test"
          - "security-check"

  # Require linear history
  - name: "Require linear history"
    conditions:
      ref_name:
        include:
          - "main"
          - "develop"
    parameters:
      required_linear_history: true

  # Require deployments to succeed
  - name: "Require deployments to succeed"
    conditions:
      ref_name:
        include:
          - "main"
    parameters:
      required_deployment_environments:
        - "production"

  # Restrict pushes that create files
  - name: "Restrict file creation"
    conditions:
      ref_name:
        include:
          - "main"
          - "develop"
    parameters:
      required_workflows:
        - "security-scan"
        - "dependency-check"

  # Security rules
  - name: "Security scanning required"
    conditions:
      ref_name:
        include:
          - "main"
          - "develop"
    parameters:
      required_workflows:
        - "security-scan"
        - "dependency-check"
        - "codeql-analysis"

  # Code quality rules
  - name: "Code quality checks"
    conditions:
      ref_name:
        include:
          - "main"
          - "develop"
          - "feature/*"
    parameters:
      required_workflows:
        - "lint"
        - "type-check"
        - "test-coverage"

  # Environment variable protection
  - name: "Protect sensitive files"
    conditions:
      ref_name:
        include:
          - "main"
          - "develop"
    parameters:
      required_workflows:
        - "secret-scanning"
      required_status_checks:
        strict: true
        contexts:
          - "secret-scanning"

# Bypass settings
bypass_actors:
  - actor_id: 1 # Repository owner
    actor_type: "RepositoryRole"
    bypass_mode: "always"
  - actor_id: 2 # Organization admins
    actor_type: "RepositoryRole"
    bypass_mode: "pull_request"

# Additional security measures
security:
  # Require signed commits
  require_signed_commits: true

  # Require branch protection
  require_branch_protection: true

  # Require security policy
  require_security_policy: true

  # Require issue templates
  require_issue_templates: true

  # Require pull request templates
  require_pull_request_templates: true

# Quality gates
quality_gates:
  # Minimum test coverage
  test_coverage:
    minimum: 80

  # Maximum complexity
  cyclomatic_complexity:
    maximum: 10

  # Maximum file size
  file_size:
    maximum: "1MB"

  # Required documentation
  documentation:
    required_files:
      - "README.md"
      - "SECURITY.md"
      - "CONTRIBUTING.md"

# Automated checks
automated_checks:
  # Dependabot alerts
  dependabot_alerts: true

  # Secret scanning
  secret_scanning: true

  # Code scanning
  code_scanning: true

  # Dependency review
  dependency_review: true
